### PR TITLE
3.0.0-preview2

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by shargon** [comment]
This will downgrade the version of the plugins, it's only for create the release?

**Comment by Tommo-L** [comment]
> This will downgrade the version of the plugins, it's only for create the release?

Yes, we'll update these plugins after release.

**Comment by Tommo-L** [comment]
wait for #213

**Comment by erikzhang** [comment]
Why will it downgrade the version of the plugins?

**Comment by erikzhang** [comment]
I will create release on this branch, but won't merge it to master.

**Pull request closed without merging**
