### PR TITLE
Change from public to protected as in level db

### LINKED ISSUE #173: RocksDB Building error
```cs
Plugins/Storage/RocksDBStore.cs(10,30): error CS0507: 'RocksDBStore.Configure()': cannot change access modifiers when overriding 'protected' inherited member 'Plugin.Configure()' [/opt/neo-plugins/src/RocksDBStore/RocksDBStore.csproj]
```

@shargon, do you have an idea?

### PR DESCRIPTION
**Pull request by vncoelho**
closes #173 

@shargon, take a look, perhaps it might be this.

### CODE REVIEW

**Comment by vncoelho** [comment]
https://github.com/neo-project/neo-modules/blob/c08ce9017ea62ef59ec69136005d40fda642537b/src/LevelDBStore/Plugins/Storage/LevelDBStore.cs#L9

**Comment by shargon** [comment]
The change it's good

**Comment by vncoelho** [comment]
Perfect, I will try to compile again as soon as possible.

**Comment by shargon** [comment]
The problem is the neo-version

**Comment by vncoelho** [comment]
The NEO version? O.o
What effectly changed from 844 to 846?

**Comment by vncoelho** [comment]
image

Maybe it is not, @shargon,

that two last commits did not changed anything related.
Anyway it might be good to update to `protected`, yes?

**Comment by shargon** [comment]
Now it pass the UT

**Comment by vncoelho** [comment]
@shargon, perhaps we can merge this PR with #174 as @cloud8little suggested.

**Comment by shargon** [comment]
I think that we should update the version of the nuget for all plugins here, what do you think?

**Comment by vncoelho** [comment]
Here or in the other PR?

**Comment by shargon** [comment]
We can close this, and join all in the other

**Pull request merged**
