### PR TITLE
dotnet 5.0

### PR DESCRIPTION
**Pull request by chenzhitong**

### CODE REVIEW

**Review by shargon — COMMENTED** [review]
Wait #403 and use shared props

**Comment by chenzhitong** [comment]
Directory.Build.props is used.

**Review by shargon — APPROVED** [review]
Wait preview4

**Comment by cloud8little** [comment]
Smoke test passed with https://github.com/neo-project/neo/pull/2083 and **NOT** upgrade Microsoft.EntityFrameworkCore.Sqlite and Microsoft.Extensions.Configuration.Json to 5.0.0

**Comment by erikzhang** [comment]
You need to upgrade the dependency too.

https://github.com/neo-project/neo-modules/blob/85bd7c371324897a20f5a7cf73ac2ece10d9f10f/src/RpcServer/RpcServer.csproj#L16

**Review by vncoelho — APPROVED** [review]

**Review by vncoelho — DISMISSED** [review]
I believe that now that `preview4` release has been postponed we could merge this PR.
Perhaps dotnet 5.0 on the `preview4` would give a good testing period by the community.

**Comment by superboyiii** [comment]
Wait preview4

**Comment by shargon** [comment]
Conflicts

**Comment by erikzhang** [comment]
@chenzhitong Please use CI01122 first.

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
