### PR TITLE
Fix response from getversion due to WS removal

### PR DESCRIPTION
**Pull request by vncoelho**

### CODE REVIEW

**Comment by cschuchardt88** [comment]
Can you post reminders on `RestServer` and `WebSocketServer` PRs?

**Review by Jim8y — DISMISSED** [review]

**Comment by Jim8y** [comment]
We still have other places that contain wsport, mind to remove them as well?

**Comment by shargon** [comment]
> We still have other places that contain wsport, mind to remove them as well?

If there are more we should remove them together

**Comment by vncoelho** [comment]
> We still have other places that contain wsport, mind to remove them as well?

I am not sure

**Comment by vncoelho** [comment]
Maybe rpcclient, lets double check

**Comment by cschuchardt88** [comment]
Try compiling the whole solution, and check for errors. After you update all the packages.

**Comment by vncoelho** [comment]
This was not compilation error,@cschuchardt88

**Comment by cschuchardt88** [comment]
But if it errors, it will let you know if anymore exist.

**Comment by vncoelho** [comment]
I was still setting up our tools that creates neo-cli client and add plugins.

I will soon compile again, but since I was able to add the plugin I think that the library does not provide compilation error, just when called.
I also added RPCClient to it.

However, thinking about the logic there must be a similar call there. Later I will check.

**Comment by Jim8y** [comment]
Just do a wsport search you will find them.

**Comment by cschuchardt88** [comment]
You want to be searching for `ws` and `websocket`

**Comment by superboyiii** [comment]
62bb544de4aeedba1e708995542dd5a
All these should be removed.

**Review by shargon — APPROVED** [review]

**Pull request merged**
