### PR TITLE
Fix storage name

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo-modules/issues/874 https://github.com/neo-project/neo/issues/3144

### CODE REVIEW

**Comment by shargon** [comment]
Please @superboyiii check it, I think that this solve the problem

**Review by vncoelho — COMMENTED** [review]
I prefer the old solution with inheritance

**Comment by vncoelho** [comment]
```cs
neo> FATAL [14:18:49.657] 	System.Collections.Generic.KeyNotFoundException
The given key 'LevelDBStore' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.Persistence.StoreFactory.GetStore(String storageEngine, String path) in /opt/neoLib/src/Neo/Persistence/StoreFactory.cs:line 48
   at Neo.NeoSystem..ctor(ProtocolSettings settings, String storageEngine, String storagePath) in /opt/neoLib/src/Neo/NeoSystem.cs:line 118
   at Neo.CLI.MainService.Start(CommandLineOptions options) in /opt/neoLib/src/Neo.CLI/CLI/MainService.cs:line 379
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'LevelDBStore' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.Persistence.StoreFactory.GetStore(String storageEngine, String path) in /opt/neoLib/src/Neo/Persistence/StoreFactory.cs:line 48
   at Neo.NeoSystem..ctor(ProtocolSettings settings, String storageEngine, String storagePath) in /opt/neoLib/src/Neo/NeoSystem.cs:line 118
   at Neo.CLI.MainService.Start(CommandLineOptions options) in /opt/neoLib/src/Neo.CLI/CLI/MainService.cs:line 379
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
/opt/start_node.sh: line 2:    77 Aborted                 (core dumped) dotnet neo-cli.dll
root@323efeae31f1:/# 
```

**Comment by vncoelho** [comment]
The name changed `LevelDBStore`

**Comment by shargon** [comment]
The object name was store and we call it by the object name

**Comment by vncoelho** [comment]
> > ```cs
> > neo> FATAL [14:18:49.657] 	System.Collections.Generic.KeyNotFoundException
> > The given key 'LevelDBStore' was not present in the dictionary.
> >    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
> >    at Neo.Persistence.StoreFactory.GetStore(String storageEngine, String path) in /opt/neoLib/src/Neo/Persistence/StoreFactory.cs:line 48
> >    at Neo.NeoSystem..ctor(ProtocolSettings settings, String storageEngine, String storagePath) in /opt/neoLib/src/Neo/NeoSystem.cs:line 118
> >    at Neo.CLI.MainService.Start(CommandLineOptions options) in /opt/neoLib/src/Neo.CLI/CLI/MainService.cs:line 379
> >    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
> >    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> >    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
> > 
> > Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'LevelDBStore' was not present in the dictionary.
> >    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
> >    at Neo.Persistence.StoreFactory.GetStore(String storageEngine, String path) in /opt/neoLib/src/Neo/Persistence/StoreFactory.cs:line 48
> >    at Neo.NeoSystem..ctor(ProtocolSettings settings, String storageEngine, String storagePath) in /opt/neoLib/src/Neo/NeoSystem.cs:line 118
> >    at Neo.CLI.MainService.Start(CommandLineOptions options) in /opt/neoLib/src/Neo.CLI/CLI/MainService.cs:line 379
> >    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
> >    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> >    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
> > /opt/start_node.sh: line 2:    77 Aborted                 (core dumped) dotnet neo-cli.dll
> > root@323efeae31f1:/# 
> > ```
> 
> This is with these changes?

Yes

**Comment by shargon** [comment]
I will fix it in neo

**Comment by vncoelho** [comment]
I think it is a better choice

> I will fix it in neo

**Pull request closed without merging**
