### PR TITLE
Fix validateaddress

### PR DESCRIPTION
**Pull request by Tommo-L**
Close https://github.com/neo-project/neo-modules/issues/352

### CODE REVIEW

**Review by shargon — APPROVED** [review]

**Comment by roman-khimov** [comment]
That makes using hex impossible not just for `validateaddress`, but also for all other calls using `AddressToScriptHash()`. What was meant by #352 is more like
```patch
--- a/src/RpcServer/RpcServer.Utilities.cs
+++ b/src/RpcServer/RpcServer.Utilities.cs
@@ -33,7 +33,7 @@ namespace Neo.Plugins
             UInt160 scriptHash;
             try
             {
-                scriptHash = AddressToScriptHash(address);
+                scriptHash = address.ToScriptHash();
             }
             catch
             {
```
Because all other calls are fine with hex values, it's only `validateaddress` that is special.

**Comment by cloud8little** [comment]
1.  Tested sendfrom/sendmany/sendtoaddress/dumpprivkey/getunclaimedgas, passed.

2.  Tested validateaddress, base58 address return true, other scripthash (big endian,little endian) return false.

3.  invokescript/invokefunction will not accept "account" as big endian, but only accept base58 address like:
```
{
  "jsonrpc": "2.0",
  "method": "invokefunction",
  "params": [
    "0xde5f57d430d3dece511cf975a8d37848cb9e0525",
    "balanceOf",
    [
      {
        "type": "Hash160",
        "value": "0x7646c5c571b77ab316815d05d1c2ede2e9ea3bb1"
      }
    ],
    [
      {
        "account": "NcJrGBZtB4rN1BfhGuLe9xvAjqUY7Q3w12",
        "scopes": "CalledByEntry"
      }
    ]
  ],
  "id": 3
}
```

```
{
  "jsonrpc": "2.0",
  "method": "invokescript",
  "params": ["0c14b13beae9e2edc2d1055d8116b37ab771c5c5467611c00c0962616c616e63654f660c1425059ecb4878d3a875f91c51ceded330d4575fde41627d5b52",[{"account":"NcJrGBZtB4rN1BfhGuLe9xvAjqUY7Q3w12","scopes":"CalledByEntry"}]],
  "id": 1
}
```

@Tommo-L https://docs.neo.org/v3/docs/zh-cn/reference/rpc/latest-version/api/invokescript.html and https://docs.neo.org/v3/docs/zh-cn/reference/rpc/latest-version/api/invokefunction.html need to be updated.

**Comment by cloud8little** [comment]
> 1. Tested sendfrom/sendmany/sendtoaddress/dumpprivkey/getunclaimedgas, passed.
> 2. Tested validateaddress, base58 address return true, other scripthash (big endian,little endian) return false.
> 3. invokescript/invokefunction will not accept "account" as big endian, but only accept base58 address like:
> 
> ```
> {
>   "jsonrpc": "2.0",
>   "method": "invokefunction",
>   "params": [
>     "0xde5f57d430d3dece511cf975a8d37848cb9e0525",
>     "balanceOf",
>     [
>       {
>         "type": "Hash160",
>         "value": "0x7646c5c571b77ab316815d05d1c2ede2e9ea3bb1"
>       }
>     ],
>     [
>       {
>         "account": "NcJrGBZtB4rN1BfhGuLe9xvAjqUY7Q3w12",
>         "scopes": "CalledByEntry"
>       }
>     ]
>   ],
>   "id": 3
> }
> ```
> 
> ```
> {
>   "jsonrpc": "2.0",
>   "method": "invokescript",
>   "params": ["0c14b13beae9e2edc2d1055d8116b37ab771c5c5467611c00c0962616c616e63654f660c1425059ecb4878d3a875f91c51ceded330d4575fde41627d5b52",[{"account":"NcJrGBZtB4rN1BfhGuLe9xvAjqUY7Q3w12","scopes":"CalledByEntry"}]],
>   "id": 1
> }
> ```
> 
> @Tommo-L https://docs.neo.org/v3/docs/zh-cn/reference/rpc/latest-version/api/invokescript.html and https://docs.neo.org/v3/docs/zh-cn/reference/rpc/latest-version/api/invokefunction.html need to be updated.

I am afraid this change will cause two problems:
1. invoke* method used to accept "0x" big-endian as "account" parameters as the signers filed, and now it can not accept.
2.  Since RpcClient will input signer for Invoke*, and it convert address to scripthash then call invoke method, which will now lead to "invalid params" result.
```cs
        public async Task<RpcInvokeResult> InvokeFunctionAsync(string scriptHash, string operation, RpcStack[] stacks, params Signer[] signer)
        {
            List<JObject> parameters = new List<JObject> { scriptHash.AsScriptHash(), operation, stacks.Select(p => p.ToJson()).ToArray() };
            if (signer.Length > 0)
            {
                parameters.Add(signer.Select(p => (JObject)p.ToJson()).ToArray());
            }
            var result = await RpcSendAsync("invokefunction", parameters.ToArray()).ConfigureAwait(false);
            return RpcInvokeResult.FromJson(result);
        }
```
Suggestion, can this change limit to validateaddress method only and not affect other rpc functions? @Tommo-L

**Comment by Tommo-L** [comment]
Fixed, @roman-khimov @shargon @cloud8little  plz reiveiw it again.

**Review by roman-khimov — APPROVED** [review]

**Review by shargon — APPROVED** [review]

**Comment by cloud8little** [comment]
Test Passed, validateaddress:
1. little-endian return false.
```
{
  "jsonrpc": "2.0",
  "method": "validateaddress",
  "params": ["9c3d8a62703e60aba0a2c9ab0996993f7fbcea35"],
  "id": 1
}
```

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "address": "9c3d8a62703e60aba0a2c9ab0996993f7fbcea35",
    "isvalid": false
  }
}
```

2. big-endian return false

```
{
  "jsonrpc": "2.0",
  "method": "validateaddress",
  "params": ["0x35eabc7f3f999609abc9a2a0ab603e70628a3d9c"],
  "id": 1
}
```

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "address": "0x35eabc7f3f999609abc9a2a0ab603e70628a3d9c",
    "isvalid": false
  }
}
```

3. base58 address return true.
```
{
  "jsonrpc": "2.0",
  "method": "validateaddress",
  "params": ["Ne3rapDVHrT7aHdFBwcq42skzgc3hgrYzd"],
  "id": 1
}
```

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "address": "Ne3rapDVHrT7aHdFBwcq42skzgc3hgrYzd",
    "isvalid": true
  }
}
```

Other rpc functions like invokefunction/invokescript and sendfrom/sendtoaddress/sendmany, dumpprivkey, getunclaimedgas not affected.

**Pull request merged**
