### PR TITLE
Add ContentTypeNotSupported OracleResponseCode

### PR DESCRIPTION
**Pull request by superboyiii**
Require: https://github.com/neo-project/neo/pull/2505
Close: https://github.com/neo-project/examples/issues/39

### CODE REVIEW

**Comment by shargon** [comment]
@superboyiii NeoFS.API is not managed by 'neo-project' but it has a dependence of 'neo' , so if we want to upgrade the neo nuget, we can't do that only in this repository

**Comment by ZhangTao1596** [comment]
NeoFS.API updated. `<PackageReference Include="NeoFS.API" Version="0.0.53" />`

**Comment by ZhangTao1596** [comment]
UT need fix.

**Comment by superboyiii** [comment]
> @superboyiii NeoFS.API is not managed by 'neo-project' but it has a dependence of 'neo' , so if we want to upgrade the neo nuget, we can't do that only in this repository

What's this? - -!
image

**Comment by superboyiii** [comment]
> @superboyiii NeoFS.API is not managed by 'neo-project' but it has a dependence of 'neo' , so if we want to upgrade the neo nuget, we can't do that only in this repository

Done

**Comment by superboyiii** [comment]
@shargon Could you review again?

**Review by shargon — APPROVED** [review]

**Pull request merged**
