### PR TITLE
Rpc limits (3x)

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo/issues/1393 for 3x

### CODE REVIEW

**Comment by shargon** [comment]
> MaxConnections default looks to be unlimited.

This was the worst problem according to our tests.

**Comment by vncoelho** [comment]
Ok, maybe let the other ones as default. I think it is not worth to reduce by half for now, @shargon.

**Comment by shargon** [comment]
The best way is a with a readTimeout, but I need to find a good solution for this.

**Comment by superboyiii** [comment]
@shargon I think it has the same design problem with https://github.com/neo-project/neo/pull/1394 ,
we should adjust config.json of  neo-cli to open interface for setting `MaxConnections `.

**Comment by shargon** [comment]
@superboyiii take a look, here is easier to configure

**Comment by shargon** [comment]
With 100 it could be vulnerable to Denial Of Service attacks in regular computers

**Comment by superboyiii** [comment]
Looks much reasonable now. I'll test it soon.

**Comment by superboyiii** [comment]
> With 100 it could be vulnerable to Denial Of Service attacks in regular computers

@shargon  Find an issue.
At first everything went smoothly. 
1. First I tried options.Limits.MaxConcurrentConnections, make it as 10. I opened 12 groups and each group has 10 threads. Requests were sent in 1 second and only 10 responses returned. It works well.
2. Secondly, I make one of these groups keeping loop for 2 minutes. It means 10 threads will keep sending requests. After 1min and 30 sec, no reponse returned. Seems 30 sec more it cost than expected but at least it worked finally.
3. Thirdly, I returned to test step 1 again, something unexpected appeared.  Almost half of 120 requests returned(the limit I set is always 10). However after I restarted neo-cli, it worked normally again.

I think it's not from your PR but some mechanism defect somewhere. But it could decrease effectiency of PR a lot.

**Comment by shargon** [comment]
> Thirdly, I returned to test step 1 again, something unexpected appeared. Almost half of 120 requests returned(the limit I set is always 10). However after I restarted neo-cli, it worked normally again.

Although it's limited to 10 concurrent, does not mean that can not serve 120 , as long as they are not concurrent they should be waiting, I think it should be the normal behavior of the server.

**Comment by superboyiii** [comment]
It doesn''t means 120 requests were sent one by one.  What I did is creating 120 threads and each one sent 1 request in 1 second at the same time. Step1 return expected result，but step3 returned different result.  I just repeat step1 in step3，they're the same behaviour.

**Comment by shargon** [comment]
You created 120 concurrent requests, but the server could enqueue and serve only 10 at same time, this dosen't mean that you can't send 120 concurrent request, means that it will spend more time, because some request need to wait and maybe some of them can fail.

**Pull request merged**
