### PR TITLE
[RpcServer] fix decimal

### PR DESCRIPTION
**Pull request by bettybao1209**

### CODE REVIEW

**Comment by cloud8little** [comment]
Test passed.

**Review by cloud8little — APPROVED** [review]

**Comment by erikzhang** [comment]
What's the difference?

**Comment by cloud8little** [comment]
> What's the difference?

0bdc5ccb16d472d974449a95360d184

the second is right.

**Comment by erikzhang** [comment]
I remember that we decided to return `BigInteger` in RPC instead of `BigDecimal`.

**Comment by bettybao1209** [comment]
> I remember that we decided to return `BigInteger` in RPC instead of `BigDecimal`.

Yes, we use `BigInteger`  in both the input and output in RPC.

**Comment by superboyiii** [comment]
@erikzhang Merge?

**Review by erikzhang — APPROVED** [review]

**Pull request merged**
