### PR TITLE
Change module command

### PR DESCRIPTION
**Pull request by shargon**
Update for https://github.com/neo-project/neo-node/pull/536

### CODE REVIEW

**Comment by nicolegys** [comment]
Thank you @shargon , I will have a test on this pr tomorrow.

**Comment by nicolegys** [comment]
Build error.
image

**Comment by shargon** [comment]
We need the nuget of https://github.com/neo-project/neo-node/pull/536 @nicolegys

**Comment by nicolegys** [comment]
@shargon Since https://github.com/neo-project/neo-node/pull/536 is merged, could you go on with this PR?

**Comment by shargon** [comment]
@erikzhang I will need the nuget of `Neo.CommandParser`, could you publish it?

**Comment by vncoelho** [comment]
@shargon, can not use the daily build?

**Comment by erikzhang** [comment]
https://www.nuget.org/packages/Neo.ConsoleService/

Done.

**Pull request merged**
