### PR TITLE
Add pending signature to ProcessInvokeWithWallet

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo-modules/issues/486

### CODE REVIEW

**Review by superboyiii — APPROVED** [review]
It works well on mine.
image

**Comment by cloud8little** [comment]
> It works well on mine.
> image

does it work after sign the result?

**Comment by superboyiii** [comment]
> > It works well on mine.
> 
> does it work after sign the result?

Yes, of course. But maybe we should add `sign` RPC, I paste incompleted context into CLI for signing. @shargon

**Review by Tommo-L — APPROVED** [review]

**Comment by vncoelho** [comment]
I agree, @superboyiii, maybe we should add this `sign` RPC.

I am finishing the tests here as well.

**Review by vncoelho — APPROVED** [review]

**Pull request merged**
