### PR TITLE
Make GetExpectedBlockSize and GetExpectedBlockSystemFee public

### PR DESCRIPTION
**Pull request by devhawk**
needed for neo express

### CODE REVIEW

**Comment by erikzhang** [comment]
Copy the code? I think these codes are simple.

**Comment by superboyiii** [comment]
> Copy the code? I think these codes are simple.

Public does no harm to the current, right?

**Comment by devhawk** [comment]
> > Copy the code? I think these codes are simple.
> 
> Public does no harm to the current, right?

I don't see how making these methods public has any negative impact on the plugin

**Comment by devhawk** [comment]
> Copy the code? I think these codes are simple.

Can't. `GetExpectedBlockSize` depends on `GetExpectedBlockSizeWithoutTransactions` which depends on private member `_witnessSize`

**Review by shargon — APPROVED** [review]

**Review by steven1227 — APPROVED** [review]

**Pull request merged**
