### PR TITLE
Update OracleService.cs

### PR DESCRIPTION
**Pull request by chenzhitong**
close https://github.com/neo-project/neo-modules/issues/494

### CODE REVIEW

**Review by shargon — COMMENTED** [review]
Could you test it if `exit` invoke `OnStop` ?

**Review by steven1227 — APPROVED** [review]

**Comment by chenzhitong** [comment]
work fine on mine.
https://user-images.githubusercontent.com/6295602/109776975-27a6ee00-7c3e-11eb-8a91-51c64337d997.mp4

**Comment by chenzhitong** [comment]
> Could you test it if `exit` invoke `OnStop` ?

yes

https://user-images.githubusercontent.com/6295602/109778179-7b660700-7c3f-11eb-9a86-49c822c65b1c.mp4

**Review by shargon — APPROVED** [review]

**Review by ProDog — APPROVED** [review]

**Comment by cloud8little** [comment]
Test passed. Exit successful when not start oracle service.

**Pull request merged**
