### PR TITLE
Neofs

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Review by vncoelho — COMMENTED** [review]
This is a real game changing.
Congratulations to all involved.

Soon we will test and make it online at NeoCompiler Eco.

**Review by vncoelho — COMMENTED** [review]
Once more, congratulations for the good work on this plugin.

Initially, it would be for RC2, right @superboyiii?

@neo-project/ngd-shanghai, are you planning to finish this plugin as a simple module like dBFT, which we can initialize a NEO-FS server easily with single node or multi node service?
The Oracle Module has the NEO-FS Api generically and will just point to the nodes initially in this service, right?

In this sense, count with us for launching it online on NeoCompiler Eco for people to start to play with large storage systems along with smart contracts.

**Comment by ZhangTao1596** [comment]
> Initially, it would be for RC2, right @superboyiii?

I don't think so.  It can't be ready in RC2.

**Comment by vncoelho** [comment]
Hi @ZhangTao1596,
What is the current status of this PR? I still see it as a draft.
Is there an expected deadline for us to try to use it? At least, for starting testing on privatenets?

Count with us for checking it.

**Comment by ZhangTao1596** [comment]
We can close this because https://github.com/neo-project/neo-modules/pull/630
If neofs storage plugin is ready, I will create another pr.

**Comment by ZhangTao1596** [comment]
> Hi @ZhangTao1596,
> What is the current status of this PR? I still see it as a draft.
> Is there an expected deadline for us to try to use it? At least, for starting testing on privatenets?
> 
> Count with us for checking it.

Hi. As I know, NeoFS is ready both on testnet and mainnet. We use the go implementation now https://github.com/nspcc-dev/neofs-node.
This pr is c# implementation. In addition, this is a dev branch which contains all codes. We will devide into three pr
Neofs-InnerRing(#630), NeoFS-Storage, NeoFS-Client.

**Comment by eaba** [comment]
@erikzhang any update on supporting neofs?

**Comment by Jim8y** [comment]
close as inactive

**Pull request closed without merging**
