### PR TITLE
fix rpc error

### PR DESCRIPTION
**Pull request by Jim8y**
This pr fix the rpc error

### CODE REVIEW

**Comment by Jim8y** [comment]
@cschuchardt88

**Review by AnnaShaleva — DISMISSED** [review]
I was sure that we've fixed all of them in #815.

**Review by AnnaShaleva — COMMENTED** [review]
Format check is failing.

**Review by vncoelho — APPROVED** [review]

**Review by cschuchardt88 — APPROVED** [review]

**Comment by vncoelho** [comment]
testing here again

**Comment by cschuchardt88** [comment]
> testing here again

Its sample simple change; shouldn't affect anything but `RpcServer` `Method` error output

**Comment by vncoelho** [comment]
Application log is fixed.

Oracle still not

```cs
#42 24.21 /opt/neo-modules/src/OracleService/OracleService.cs(260,65): error CS1503: Argument 3: cannot convert from 'byte[]' to 'Neo.Cryptography.ECC.ECCurve' [/opt/neo-modules/src/OracleService/OracleService.csproj]
```

**Comment by cschuchardt88** [comment]
> Application log is fixed.
> 
> Oracle still not
> 
> ```cs
> #42 24.21 /opt/neo-modules/src/OracleService/OracleService.cs(260,65): error CS1503: Argument 3: cannot convert from 'byte[]' to 'Neo.Cryptography.ECC.ECCurve' [/opt/neo-modules/src/OracleService/OracleService.csproj]
> ```

`net8.0` upgrade will fix it...

**Comment by cschuchardt88** [comment]
@shargon currently `main.yml` doesn't do a `dotnet build` on all projects on this repo...

**Comment by shargon** [comment]
> @shargon currently `main.yml` doesn't do a `dotnet build` on all projects on this repo... Which is way is was missed.

I don't know, time ago neo-modules was not maintained by core devs...

**Pull request merged**
