### PR TITLE
fix insufficient networkfee in RpcClient

### PR DESCRIPTION
**Pull request by bettybao1209**
The decimal of network fee in RpcClient and RpcServer is different, resulting in `insuffient funds` exception.

### CODE REVIEW

**Comment by erikzhang** [comment]
I think use floating-point numbers in JSON is not safe. Especially in the case of expressing prices.

**Comment by bettybao1209** [comment]
> I think use floating-point numbers in JSON is not safe. Especially in the case of expressing prices.

If not, it may be knida confusing for users when invoking `calculatenetworkfee` in RPCServer.

**Comment by erikzhang** [comment]
We should uniformly use `long` to ensure accuracy.

**Comment by bettybao1209** [comment]
> We should uniformly use `long` to ensure accuracy.

But currently we use float value for json output like json["gasconsumed"].

**Comment by erikzhang** [comment]
> But currently we use float value for json output like json["gasconsumed"].

I think we should use `long` for JSON output.

**Comment by bettybao1209** [comment]
So should we uniform both the user input and the JSON output in `long` type?

**Comment by erikzhang** [comment]
For JSON, I think we should use `long` for both requests and response.

**Comment by chenzhitong** [comment]
> For JSON, I think we should use `long` for both requests and responses.

The asset amount(fees and NEP-17 tokens) is now in `decimal` format in both neo-cli and RpcServer.

**neo-cli command:**
deploy
invoke
balanceof
totalsupply
transfer
etc.

**RpcServer：**
 calculatenetworkfee
 getapplicationlog
 getblock
 getblockheader
 getrawtransaction
 getunclaimedgas
 getwalletunclaimedgas
 invokecontractverify
 invokefunction
 invokescript
 sendfrom
 sendmany
 sendtoaddress
 getnep17balances
 getnep17transfers
 getwalletbalance

**Comment by roman-khimov** [comment]
> I think use floating-point numbers in JSON is not safe.

They really are, we had problems with rounding errors.

> For JSON, I think we should use long for both requests and responses.

But we can wrap them into strings, returning `"value": "0.12345678"` instead of `"value": 0.12345678`. This representation is much more convenient to me (especially for everything that is not GAS or NEO where the number of decimals is well-known, it's not for $RANDOM_TOKEN). And it avoids any losses when converting to/from JSON.

I mean `BigDecimal.ToString()` doesn't introduce any rounding errors and neither does `TryParse()`, so we just need to avoid going through floating point everywhere we're dealing with these values and we'll be fine.

**Comment by erikzhang** [comment]
Wrapping `BigInteger` into `string` in JSON is okay for me.

**Review by chenzhitong — APPROVED** [review]

**Comment by bettybao1209** [comment]
move to https://github.com/neo-project/neo-modules/pull/505

**Pull request closed without merging**
