### PR TITLE
Fix RpcServer RegisterMethods

### PR DESCRIPTION
**Pull request by ProDog**
`ApplicationLogs` and `RpcNep5Tracker` can't added in handlers if `RpcServerPlugin` loaded first.
This could lead to https://github.com/neo-project/neo-modules/issues/236 .

### CODE REVIEW

**Comment by superboyiii** [comment]
Tested: PASS
I replace this version on my older version, it works normally now.

**Comment by shargon** [comment]
Then, what is the sense of this method? https://github.com/neo-project/neo-modules/blob/57f2ab56e5bc2946e5adc7f37bbeb82bd3c5e6d1/src/ApplicationLogs/LogReader.cs#L33

**Comment by ProDog** [comment]
There  registered it if the plugin in `handlers`:
https://github.com/neo-project/neo-modules/blob/57f2ab56e5bc2946e5adc7f37bbeb82bd3c5e6d1/src/RpcServer/RpcServerPlugin.cs#L41

**Comment by gsmachado** [comment]
Nice! This bug was bugging me for some time. 😄

**Pull request merged**
