### PR TITLE
crlf replaced by lf

### PR DESCRIPTION
**Pull request by vncoelho**
close https://github.com/neo-project/neo-modules/issues/891

### CODE REVIEW

**Comment by vncoelho** [comment]
There is a strange error, trying to fix this "corrupted" file

**Comment by cschuchardt88** [comment]
@vncoelho Please `close` PR and do https://github.com/neo-project/neo-modules/issues/891#issuecomment-2016009178

**Comment by vncoelho** [comment]
I will double check

**Comment by cschuchardt88** [comment]
@vncoelho Checkout #893

**Comment by vncoelho** [comment]
Looks good,but what is the difference from the PR I opened? The file fix looks the same.
The other change looks good, is to avoid for future,right?

**Comment by cschuchardt88** [comment]
@vncoelho I could change `config.json` back to `CRLF`; see notes _**below**_ for reason why.

Add to `.gitattributes` File
---
- `*.json text eol=lf`
  - _**Note:** This will automatically normalize & change line endings for all `*.json` files on **push/commit**_.

**Comment by Jim8y** [comment]
@vncoelho the code itself is right, but you have to update your local setting.

**Comment by vncoelho** [comment]
> @vncoelho I could not change `config.json` back to `CRLF`; see notes _**below**_ for reason why.
> 
> You Add to `.gitattributes` File
> ---
> - `*.json text eol=lf`
>   - _**Note:** This will automatically normalizes & changes line endings for all `*.json` files on **push/commit**_.

Great, I was thinking about some change to enforce it. It is great that you found the solution.

**Comment by vncoelho** [comment]
> @vncoelho the code itself is right, but you have to update your local setting.

I do not know what you are trying to say,@vncoelho.
The local setting is the same as before.

**Comment by cschuchardt88** [comment]
> Great, I was thinking about some change to enforce it. It is great that you found the solution.

@vncoelho We had problems last year with this happening; guess I missed a file.

**Comment by dusmart** [comment]
I faced the same problem, too.

Seems that the crlf are introduced in https://github.com/neo-project/neo-modules/pull/865/files. 

This fix should be sufficient.

**Comment by cschuchardt88** [comment]
> * *.json text eol=lf

@vncoelho 
- Add this line `*.json text eol=lf` to `.gitattributes` file for this PR to be complete.

**Comment by vncoelho** [comment]
> @vncoelho 
> - Add this line `*.json text eol=lf` to `.gitattributes` file for this PR to be complete.

Sure, you can add if you want or open in a new PR.

**Comment by vncoelho** [comment]
Soon I will be in the computer as well.

**Comment by vncoelho** [comment]
> @vncoelho
> 
>     * Add this line `*.json text eol=lf` to `.gitattributes` file for this PR to be complete.

done

**Review by shargon — APPROVED** [review]

**Pull request merged**
