### PR TITLE
Revert "Added AspNetCore (#863)"

### PR DESCRIPTION
**Pull request by vncoelho**
This reverts commit e9e7a07a3e170852b32784c5a48456c63fe55498.

if https://github.com/neo-project/neo/pull/3066 is merged

### CODE REVIEW

**Review by cschuchardt88 — APPROVED** [review]
This needs to be done.  PR https://github.com/neo-project/neo/pull/3067 fixes issue.

**Comment by vncoelho** [comment]
I do not think, so @cschuchardt88 
I tried here and there are compilations problems without this change.

**Comment by cschuchardt88** [comment]
NVM close this.

This still needs to be done, Because no `neo.dll` that imports `asp.net` framework.

**Comment by vncoelho** [comment]
@shargon, too much instability on that other change. I am still not feeling safe to go. 

The changes are requesting too much for the basic environment to build and run a simple client.

**Comment by cschuchardt88** [comment]
Let me fix `RestServer` 1st, and problem gone.

**Comment by vncoelho** [comment]
I am not in hurry, most of the current working PRs are made by you @cschuchardt88 ....aheuaheuahea
As soon as everything is clear it will look good to me.
But fell free to move on if you guys fell it is good.

**Comment by cschuchardt88** [comment]
It's just user error on your part. I tested everything with and without docker.

**Pull request closed without merging**
