### PR TITLE
RpcServer should support missing params request property

### LINKED ISSUE #768: RpcServer should support missing params request property
Some RPC methods (such as getbestblockhash) don't have any parameters. However, if the caller doesn't include an empty array in the request, `ProcessRequestAsync` returns an `Invalid Request` error message.

I recommend updating `ProcessRequestAsync` to validate the `params` property is an array if present and pass an empty array into the RPC method if not present

From [JSON-RPC 2.0 specification](https://www.jsonrpc.org/specification#request_object):

> **params**: A Structured value that holds the parameter values to be used during the invocation of the method. This member MAY be omitted.

### PR DESCRIPTION
**Pull request by devhawk**
Fixes #768

Note, there are no tests for RpcServer currently. Should I add one for this functionality?

### CODE REVIEW

**Comment by roman-khimov** [comment]
See also #747.

**Comment by devhawk** [comment]
> See also #747.

I think this is a cleaner fix than #747, but I'm cool with merging either. @shargon make the call

**Review by shargon — APPROVED** [review]

**Comment by shargon** [comment]
> > See also #747.
> 
> I think this is a cleaner fix than #747, but I'm cool with merging either. @shargon make the call

Agree

**Review by superboyiii — APPROVED** [review]

**Comment by superboyiii** [comment]
Tested OK.

**Comment by superboyiii** [comment]
@erikzhang Could you have a look?

**Pull request merged**
