### PR TITLE
Fix invokefunction

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo-modules/issues/573

### CODE REVIEW

**Comment by Qiao-Jin** [comment]
Default `MaxGasInvoke` is 20. For the specified problem in #573, same error would still occur even with this PR patched. Maybe should also add a log reminding user to increase `MaxGasInvoke` in such cases?

https://github.com/neo-project/neo-modules/blob/e77f07401d81724b088b65fd6c63b428c6625837/src/RpcServer/RpcServer/config.json#L13

**Comment by superboyiii** [comment]
I think it's OK, we can wait for @snowypowers 's response.

**Comment by shargon** [comment]
> Maybe should also add a log reminding user to increase MaxGasInvoke in such cases?

Any error will be catched in line 

https://github.com/neo-project/neo-modules/pull/574/files#diff-f4edf66b165030d591ad126a9d9a91daeed2f74df8c6aff0150a46fa193e5d4eR185

**Comment by snowypowers** [comment]
Yes this should work out for my scenario. I forgot to mention I did set my config's MaxGasInvoke to 10000 so this fix will help me out!

**Review by superboyiii — APPROVED** [review]

**Review by Qiao-Jin — APPROVED** [review]

**Pull request merged**
