### PR TITLE
Add StackItem ToJson

### PR DESCRIPTION
**Pull request by bettybao1209**
close https://github.com/neo-project/neo-modules/issues/218  https://github.com/neo-project/neo-devpack-dotnet/issues/218

### CODE REVIEW

**Comment by erikzhang** [comment]
Please use https://github.com/neo-project/neo/pull/1569

**Comment by Tommo-L** [comment]
We should merge this first, as neo-project/neo#1569 isn't included in `core-preview2`.

**Comment by Tommo-L** [comment]
@bettybao1209 Could update this pr, according to  neo-project/neo#1569

**Comment by erikzhang** [comment]
Use `Neo.3.0.0-CI00892` directly.

**Comment by Tommo-L** [comment]
Ok

**Comment by ProDog** [comment]
plz merge this @erikzhang

**Pull request merged**
