### PR TITLE
Update devcontainer.json

### PR DESCRIPTION
**Pull request by vncoelho**

### CODE REVIEW

**Comment by cschuchardt88** [comment]
Why are you adding this when this repo is moving?

**Comment by vncoelho** [comment]
It is used for my tests and that PR is not yet merged.

**Comment by cschuchardt88** [comment]
> It is used for my tests and that PR is not yet merged.

Yes, but the repo it moving to already has one in there you should be changing that one if it needs it.

**Comment by shargon** [comment]
Repository moved to [neo](https://github.com/neo-project/neo), please re-open there

**Pull request closed without merging**
