### PR TITLE
Updated `.editorconfig` & Applied Changes

### PR DESCRIPTION
**Pull request by cschuchardt88**
- Updated .editorconfig and run code analyze
- Added `.gitattibutes`

Used `.editorconfig` from `neo` repo

### CODE REVIEW

**Comment by superboyiii** [comment]
Is this OK that namespace changed after format?

**Comment by cschuchardt88** [comment]
hmm that's weird!!! 😭

**Comment by cschuchardt88** [comment]
@superboyiii Must be you. I see no such change.

image

**Comment by superboyiii** [comment]
Maybe I'm in the wrong way for your editconfig? How should it be applied?
image

**Comment by cschuchardt88** [comment]
@superboyiii this is what i ran
image

**Comment by superboyiii** [comment]
Yes, when I use 

> @superboyiii this is what i ran image

Yes, this works when I turned `Fix all warnings and errors set in EditorConfig` to `Fix analyzer warnings and errors set in EditorConfig`

**Review by shargon — APPROVED** [review]

**Pull request merged**
