### PR TITLE
limit free gas

### PR DESCRIPTION
**Pull request by Ashuaidehao**
Close https://github.com/neo-project/neo/issues/2670

### CODE REVIEW

**Review by shargon — COMMENTED** [review]
Why can be more flexible or be able to configure it

**Comment by Ashuaidehao** [comment]
It has 34 times gas costs elasticity now, which is enough for normal contracts.

**Review by shargon — APPROVED** [review]

**Review by Liaojinghui — DISMISSED** [review]

**Comment by shargon** [comment]
@Ashuaidehao change to develop branch?

**Comment by Ashuaidehao** [comment]
> @Ashuaidehao change to develop branch?

OK.

**Review by shargon — APPROVED** [review]

**Pull request merged**
