### PR TITLE
Update RpcApplicationLog.cs in RpcClient

### PR DESCRIPTION
**Pull request by chenzhitong**
Sync with https://github.com/neo-project/neo-modules/pull/380

### CODE REVIEW

**Review by shargon — APPROVED** [review]

**Comment by ProDog** [comment]
Need add the `TriggerType` parameter here?😃
https://github.com/neo-project/neo-modules/blob/3ab2871ab30a90e6dcb2b14ff2e59631f40fa59f/src/RpcClient/RpcClient.cs#L540

**Comment by ProDog** [comment]
It's good for me.

image

**Comment by chenzhitong** [comment]
> It's good for me.
> 
> image

image

**Comment by superboyiii** [comment]
Works well on mine.
image

**Review by superboyiii — APPROVED** [review]

**Review by shargon — APPROVED** [review]

**Pull request merged**
