### PR TITLE
[RpcNep17Tracker]Fix null exception when OnPersist before OnSystemLoaded

### PR DESCRIPTION
**Pull request by ZhangTao1596**
Fix node start failed with all plugins on osx.

**Reason**
 Since persist genesis block and `OnSystemLoaded` of plugins execute in different threads. `Plugin.OnPersist` might be called before `Plugin.OnSystemLoaded` on different os. If so, there will be object null exception in `RpcNep17Tracker`.

### CODE REVIEW

**Comment by shargon** [comment]
We should find another way

**Comment by superboyiii** [comment]
Any way, it fixed the problem. Test **Pass** on mine.

**Comment by erikzhang** [comment]
I think we should revert neo-project/neo#2368

**Comment by ZhangTao1596** [comment]
> I think we should revert neo-project/neo#2368

Why?

**Comment by erikzhang** [comment]
> Plugin.OnPersist might be called before Plugin.OnSystemLoaded on different os.

It is impossible.

**Comment by ZhangTao1596** [comment]
> > Plugin.OnPersist might be called before Plugin.OnSystemLoaded on different os.
> 
> It is impossible.

It does. We persist genesis block in `Blockchain` constructor.

**Comment by erikzhang** [comment]
Please check neo-project/neo#2397

**Comment by ZhangTao1596** [comment]
Close this because neo-project/neo#2397 can make all plugins work as we expect.

**Pull request closed without merging**
