### PR TITLE
Ignore config duplicate error

### LINKED ISSUE #726: Publish of OracleService dependencies has problems due to CONFIG files with same name
After publishing each plugin, we use to get specific dependencies, such as (for `OracleService`):

```
Google.Protobuf.dll
Grpc.AspNetCore.Server.ClientFactory.dll
Grpc.AspNetCore.Server.dll
Grpc.Core.Api.dll
Grpc.Net.Client.dll
Grpc.Net.ClientFactory.dll
Grpc.Net.Common.dll
Neo.FileStorage.API.dll
```
Something changed recently and our script is not finding these files anymore inside the published directory.

We use to use the following command:
```cs
dotnet publish -c Release -o /opt/neo-modules/src/OracleService/app
```

We are just finding them at:
```
/root/.nuget/packages/grpc.net.clientfactory/2.36.0/lib/net5.0/Grpc.Net.ClientFactory.dll
/root/.nuget/packages/grpc.net.clientfactory/2.36.0/lib/netstandard2.1/Grpc.Net.ClientFactory.dll
/root/.nuget/packages/neofs.api/3.3.0/lib/net6.0/Neo.FileStorage.API.dll
etc...
```

### LINKED ISSUE #727: Path conflict from config.json when publishing OracleService to get dependency
**Describe the bug**
Path conflict from config.json when publishing OracleService to get dependency since the same name of ./RpcServer/config.json and ./OracleService/config.json is the same, they will both be published in the same path.
**It's important since we need these dependency like Grpc.xxx.dll and Neo.FileStorage.API.dll for OracleService.**

**To Reproduce**
dotnet publish in OracleService

**Expected behavior**
```
Determining projects to restore...
  All projects are up-to-date for restore.
  RpcServer -> E:\Release\3.3.0\neo-modules\src\RpcServer\bin\Debug\net6.0\RpcServer.dll
  OracleService -> E:\Release\3.3.0\neo-modules\src\OracleService\bin\Debug\net6.0\OracleService.dll
C:\Program Files\dotnet\sdk\6.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: E:\Release\3.3.0\neo-modules\src\RpcServer\config.json, E:\Release\3.3.0\neo-modules\src\OracleService\config.json. [E:\Release\3.3.0\neo-modules\src\OracleService\OracleService.csproj]
```

**Platform:**
 - Version [neo-cli 3.3.0]

### PR DESCRIPTION
**Pull request by ZhangTao1596**
Close #726
Close #727

### CODE REVIEW

**Review by superboyiii — DISMISSED** [review]
Since we only want to solve dependency publish when config.json has conflict, I think it's OK to ignore these config with the same name.

**Comment by ZhangTao1596** [comment]
> @ZhangTao1596 Should apply it not only on OracleService but also `ApplicationLogs`, `TokensTracker` and `StateService`.

Done.

**Review by shargon — COMMENTED** [review]
Copy it into https://github.com/neo-project/neo-modules/blob/1aeab6290d5c7b2bf30380ec4e93f4f4abe8b546/src/Directory.Build.props#L14 ?

**Comment by ZhangTao1596** [comment]
> Copy it into
> 
> https://github.com/neo-project/neo-modules/blob/1aeab6290d5c7b2bf30380ec4e93f4f4abe8b546/src/Directory.Build.props#L14
> 
> ?

Done.

**Comment by shargon** [comment]
The file neo-modules/src/Directory.Build.props seems not changed

**Comment by ZhangTao1596** [comment]
> The file neo-modules/src/Directory.Build.props seems not changed

Sorry, my mistake. Now it's ok.

**Comment by shargon** [comment]
Tested?

**Comment by superboyiii** [comment]
Move it to Directory.Build.props doesn't get the expected behaviour. For example: OracleService/config.json is replaced by RpcServer/config.json, although it's in OracleService publish folder.
```
C:\Program Files\dotnet\sdk\6.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: E:\PR-test\modules-PR#729\neo-modules\src\RpcServer\config.json, E:\PR-test\modules-PR#729\neo-modules\src\OracleService\config.json. [E:\PR-test\modules-PR#729\neo-modules\tests\Neo.Plugins.OracleService.Tests\Neo.Plugins.OracleService.Tests.csproj]
```

**Review by erikzhang — APPROVED** [review]

**Comment by superboyiii** [comment]
Test OK by `dotnet publish -maxcpucount:1`

**Review by superboyiii — APPROVED** [review]

**Pull request merged**
