### PR TITLE
fix main.yml

### PR DESCRIPTION
**Pull request by cloud8little**

### CODE REVIEW

**Comment by shargon** [comment]
what status left?

**Comment by superboyiii** [comment]
@shargon Do we need to do something to shut down Travis to pass the check? I just removed the setting file but it seems still `Waiting for status to be reported`.

**Comment by shargon** [comment]
@superboyiii 
image

**Comment by superboyiii** [comment]
@shargon Seems the issue is here. Could you do this?
https://github.community/t/expected-waiting-for-status-to-be-reported/18001

**Comment by shargon** [comment]
Done, this was the problem. Now require 

image

**Pull request merged**
